# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: COS 324 Notes
tagline: COS 324 - Introduction to Machine Learning
description: Princeton University, Fall 2022
author: Simon Park
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://princeton-introml.github.io" # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc1
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Registrar:
    - 'https://registrar.princeton.edu/course-offerings/course-details?term=1232&courseid=014294'
footer_content:

# Collections for website data
collections:
  staffers:
  authors:
  modules:

# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
      subpath: '/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
